**Step-1: Read the packages**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2: Read the datasets**

In [3]:
visa_df=pd.read_csv(r"C:\Users\Admin\OneDrive\Documents\EDA\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [5]:
bank_df=pd.read_csv(r"C:\Users\Admin\OneDrive\Documents\EDA\bank.csv",sep=';')
bank_df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

**Step-3:Data Qucik Checks**

**us visa_df** 

- visa_df.shape

- visa_df.size

- head

- tail 

- dtypes

- columns

- isnull

- info

In [6]:
visa_df.shape
print(f'The number of rows are:{visa_df.shape[0]}')
print(f'The number of columns are:{visa_df.shape[1]}')

The number of rows are:25480
The number of columns are:12

In [7]:
type(visa_df)

pandas.core.frame.DataFrame

In [8]:
visa_df.size
# Number of entries

305760

In [9]:
cols=visa_df.columns
cols
# What are the columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [10]:
# what is the index of 'yr_of_estab'
cols.index('yr_of_estab')

AttributeError: 'Index' object has no attribute 'index'

In [11]:
cols=visa_df.columns.tolist()
cols.index('yr_of_estab')

6

In [12]:
visa_df.head(3)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied

In [13]:

visa_df.tail(3)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.85,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.77,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.91,Year,Y,Certified

In [14]:
# How you are seeing a df in the numpy language
# pandas ==== Numpy
# I df 25480 rows 12 columns  25480x12
# Numpy : Bro i have a array having 12 values: 12 columns
#        these list are repeating 25480 time 

np.array([[1,2,3,4]]).shape  # I have a list of 4 value 1 time
np.array([[1,2,3,4],[10,20,30,40]]).shape # I have a list of 4 values 2 times 
#  4 columns 2 rows

(2, 4)

In [15]:
#[[1,2,3.....12],[],[].......25480]
visa_df # pandas
visa_df.values # numpy arrays

array([['EZYV01', 'Asia', 'High School', ..., 'Hour', 'Y', 'Denied'],
       ['EZYV02', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV03', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Denied'],
       ...,
       ['EZYV25478', 'Asia', "Master's", ..., 'Year', 'N', 'Certified'],
       ['EZYV25479', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV25480', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Certified']],
      shape=(25480, 12), dtype=object)

**loc-iloc**

In [16]:
#visa_df.iloc[rows,columns]
#visa_df.iloc[start:stop:step,start:stop:step]
visa_df.iloc[2:6,3:7]
# rows: 2:6  2,3,4,5
# columns: 3:7, 3,4,5,6

  has_job_experience requires_job_training  no_of_employees  yr_of_estab
2                  N                     Y            44444         2008
3                  N                     N               98         1897
4                  Y                     N             1082         2005
5                  Y                     N             2339         2012

In [17]:
# loc will use ful we can provide direct column names
# no need of indexes
cols=['has_job_experience','requires_job_training']
visa_df.loc[2:6,cols]

  has_job_experience requires_job_training
2                  N                     Y
3                  N                     N
4                  Y                     N
5                  Y                     N
6                  N                     N

In [ ]:
visa_df.iloc[2:6,3:7]
cols=['has_job_experience','requires_job_training']
visa_df.loc[2:6,cols]

In [18]:
visa_df.iloc[[100,200,300]]
visa_df.iloc[[100,200,300],:3]
visa_df.iloc[[100,200,300],[3,9]]

    has_job_experience unit_of_wage
100                  Y         Year
200                  Y         Year
300                  Y         Year

In [19]:
# Every student should undersnd
# 1D and 2D 
# list []   Numpy : 1D   Pandas === series
# list [[]] Numpy : 2D   Pandas === dataframe

In [20]:
visa_df  # df: column names

visa_df['continent'] # series  no column name

0          Asia
1          Asia
2          Asia
3          Asia
4        Africa
          ...
25475      Asia
25476      Asia
25477      Asia
25478      Asia
25479      Asia
Name: continent, Length: 25480, dtype: object

In [21]:
visa_df.values

array([['EZYV01', 'Asia', 'High School', ..., 'Hour', 'Y', 'Denied'],
       ['EZYV02', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV03', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Denied'],
       ...,
       ['EZYV25478', 'Asia', "Master's", ..., 'Year', 'N', 'Certified'],
       ['EZYV25479', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV25480', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Certified']],
      shape=(25480, 12), dtype=object)

In [22]:
visa_df['continent'].values

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

In [23]:
visa_df
visa_df['continent'] # 1D S
visa_df[['continent']] # 2D df
rows=[100,200,300]
visa_df.iloc[rows,3] # 1d S
visa_df.iloc[rows,[3]] # 2D D
visa_df.loc[rows,'continent'] # 1 D
visa_df.loc[rows,['continent']] # 2D

    continent
100      Asia
200      Asia
300      Asia

In [24]:
visa_df # df  2d
visa_df.values # arrays  2d 
# there are 12 columns
# a list has 12 values 
# list is repeating 25480 rows

array([['EZYV01', 'Asia', 'High School', ..., 'Hour', 'Y', 'Denied'],
       ['EZYV02', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV03', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Denied'],
       ...,
       ['EZYV25478', 'Asia', "Master's", ..., 'Year', 'N', 'Certified'],
       ['EZYV25479', 'Asia', "Master's", ..., 'Year', 'Y', 'Certified'],
       ['EZYV25480', 'Asia', "Bachelor's", ..., 'Year', 'Y', 'Certified']],
      shape=(25480, 12), dtype=object)

In [25]:
visa_df['continent']
visa_df['continent'].values # raw data

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

In [26]:
visa_df[['continent','case_status']]
visa_df[['continent','case_status']].values

array([['Asia', 'Denied'],
       ['Asia', 'Certified'],
       ['Asia', 'Denied'],
       ...,
       ['Asia', 'Certified'],
       ['Asia', 'Certified'],
       ['Asia', 'Certified']], shape=(25480, 2), dtype=object)

In [30]:
# 1D is only one list : Raw data of a specific column
visa_df['continent'].values # [25480]

# 2d is a list has 2 values : DF 2 column

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'],
      shape=(25480,), dtype=object)

In [31]:
visa_df['continent'] # S
visa_df[['continnet']] # D
visa_df.iloc[[100,200,300],3] # S
visa_df.iloc[[100,200,300],[3]] # D
visa_df.loc[[100,200,300],'continnet'] # S
visa_df.loc[[100,200,300],['continnet']] # D

KeyError: "None of [Index(['continnet'], dtype='object')] are in the [columns]"

**dtypes**

- every series is a key value pair

- every series is dictionary

- in dictionary if we want keys: .keys()

- in dictionary if we want values: .values

In [32]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

**task-1**

In [33]:
keys=visa_df.dtypes.keys().tolist()
values=visa_df.dtypes.values.tolist()
pd.DataFrame(zip(keys,values),columns=['Name','Data type'])

                     Name Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

In [23]:
visa_df.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [41]:
df=pd.DataFrame(visa_df.dtypes).reset_index()
df.columns=['Name','Data type']
df

                     Name Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

**task-2**

In [49]:
visa_df.dtypes
# idea 
# extract keys and values
# apply the for loop on values
# for i,j in zip(values,keys):
#  if i =='object':
#      j  

keys=visa_df.dtypes.keys().tolist()
values=visa_df.dtypes.values.tolist()
cat,num=[],[]
for i,j in zip(keys,values):
    if j=='object':
        cat.append(i)
    else:
        num.append(j)
cat,num

(['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'region_of_employment',
  'unit_of_wage',
  'full_time_position',
  'case_status'],
 [dtype('int64'), dtype('int64'), dtype('float64')])

**select_dtypes**

In [54]:
visa_df.select_dtypes(include='object').columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [56]:
visa_df.select_dtypes(exclude='object').columns

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')