In [ ]:
==================== Data Analysis =============================
1. Pandas         :  Data frame analysis
2. Numpy          :  Numerical analysis
3. matplotlib     :  Graphs and plots
4. seaborn        :  plots
5. Bokhe         :   plots
6. plotly         :  plots

=================== Machine Learning ============================
7. stats          : for statistical models
8. scikit-learn(sklearn) :  ML models

===================  Deep learning ============================
9. opencv         : Computer vision
10. pillow        : Image operations
11. tensorflow    : Neural Network creations (developed by google)
12. keras         : NN
13. pytorch       : alternative package of tensorflow (facebook meta)

==================== NLP ========================================
14. NLTK          : Natural language toolkit
15. SpaCy         : Alternative to NLTK
16. wordcloud     : most frequent occured words       

======================= Scarapping =================================
17. SqLite        : Data base creation
18. Beautiful soup
19. Selenium

======================== API creations ===========================
20. Flask
21. FastAPI
22. Gradio
23. Django
======================= UI app creation =========================
24.Streamlit

===================== Transfer learning models(DL) ===========
25. Mobilenet
26. Resnet
27. VGGnet
28. Inception
29. Yolo    :  Ultralytics

===================== Transfer learning models(NLP) ===========
30. Word2vec
31. GloVe

======================== Hugging Face Transformers ===============
32. BERT   : Bi Directional Encoder representation of Transformers

========================== Allen NLP =======================
33. Allen NLP packages

================== GenAI =============================
34. LangChain
35. Google GeminiAi realted pcakges
36. OpenAI GPT realted packages
37. Amazon BedRock realted packages
38. Meta Llama  related packages
39. Anthropic

==================== Image and Video Generations ==============
39. GAN models realted packages
40. SORA related packages
41. nano banana

=================== Model deployment (MlOps)===================
41. mlflow using databricks
42. kubeflow (GCP account)

==================== Cloud applications =====================
43. Azure ML realted packages
44. GCP VertexAI related packages
45. AWS Sagemaker realted packages

==================== small ===================================
46. time
47. logging
48. math
49. random
50. env
51. os

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
Names=['Ramesh','Suresh','Sathish','Mahesh']
Age=[20,22,24,26]

**Step-1:Create a Dataframe**

In [3]:
#pd.DataFrame(data,index,columns,dtype,copy)
pd.DataFrame(Names)
#pd.DataFrame(Names,'Names') # Names assume as index
#pd.DataFrame(Names,columns='Names') # Columns array 
pd.DataFrame(Names,columns=['Names'])

     Names
0   Ramesh
1   Suresh
2  Sathish
3   Mahesh

In [10]:
pd.DataFrame(Names,'Names')

TypeError: Index(...) must be called with a collection of some kind, 'Names' was passed

In [7]:
pd.DataFrame(Names,columns=['Names'])

     Names
0   Ramesh
1   Suresh
2  Sathish
3   Mahesh

In [26]:
#pd.DataFrame(data,index,columns,dtype,copy)
pd.DataFrame(Names)
pd.DataFrame(Names,columns=['Names'])
pd.DataFrame(Names,
             index=['A','B','C','D'],
             columns=['Names'])

     Names
A   Ramesh
B   Suresh
C  Sathish
D   Mahesh

In [28]:
Names=['Ramesh','Suresh','Sathish','Mahesh']
Age=[20,22,24,26]
#pd.DataFrame(data,index,columns)
pd.DataFrame(Names,Age)

          0
20   Ramesh
22   Suresh
24  Sathish
26   Mahesh

In [9]:
Names=['Ramesh','Suresh','Sathish','Mahesh']
Age=[20,22,24,26]
DATA=[Names,Age]
#pd.DataFrame(data,index,columns)
pd.DataFrame(DATA).T

         0   1
0   Ramesh  20
1   Suresh  22
2  Sathish  24
3   Mahesh  26

In [11]:
Names=['Ramesh','Suresh','Sathish','Mahesh']
Age=[20,22,24,26]
DATA=zip(Names,Age)
pd.DataFrame(DATA,
             columns=['Names','Age'])

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24
3   Mahesh   26

**Step-2: Add a new column to already an existed df**

In [13]:
Names=['Ramesh','Suresh','Sathish','Mahesh']
Age=[20,22,24,26]
DATA=zip(Names,Age)
df=pd.DataFrame(DATA,columns=['Names','Age'])

In [15]:
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24
3   Mahesh   26

In [20]:
#df[col_name] # Selection
           # updation
           # creation

In [22]:
df['Names']

0     Ramesh
1     Suresh
2    Sathish
3     Mahesh
Name: Names, dtype: object

In [24]:
df['Age']=[30,32,34,36]

In [51]:
df

     Names  Age
0   Ramesh   30
1   Suresh   32
2  Sathish   34
3   Mahesh   36

In [26]:
df['City']=['Hyd','Pune','Blr','Bihta']
df

     Names  Age   City
0   Ramesh   30    Hyd
1   Suresh   32   Pune
2  Sathish   34    Blr
3   Mahesh   36  Bihta

- created a dataframe with one column

- learned how to add a column names

- learned how to change the index

- created a dataframe with two coulmns uisng zip

- understood how to select update and create new column with already existed dataframe

**Step-3: How to add data to empty dataframe**

In [30]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [36]:
#df['Names'] # Im selcting a column : Names
df['Names']=['Ramesh','Suresh','Sathish']
df['Age'] =[20,22,24]
df['City']=['Hyd','Blr','Chennai']
df

     Names  Age     City
0   Ramesh   20      Hyd
1   Suresh   22      Blr
2  Sathish   24  Chennai

**Step-4: Create a Dataframe using Dictionary**

In [40]:
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
   'City':['Hyd','Pune','Delhi']}
d

{'Names': ['Ramesh', 'Suresh', 'Sathish'],
 'Age': [20, 22, 24],
 'City': ['Hyd', 'Pune', 'Delhi']}

In [42]:
df=pd.DataFrame(d)
df
# Keys become columns
# Values become rows

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Delhi

In [44]:
d={'Names':'Ramesh',
  'Age':20,
   'City':'Hyd'}
pd.DataFrame(d)

ValueError: If using all scalar values, you must pass an index

In [52]:
#If using all scalar values, you must pass an index
d={'Names':'Ramesh',
  'Age':20,
   'City':'Hyd'}
pd.DataFrame(d,index=[0,1,2])

    Names  Age City
0  Ramesh   20  Hyd
1  Ramesh   20  Hyd
2  Ramesh   20  Hyd

**Step-5: drop a new column**

In [55]:
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
   'City':['Hyd','Pune','Delhi']}
df=pd.DataFrame(d)
df

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Delhi

In [ ]:
df.drop(Lables,axis=0,index,columns,inplace=True)  # Index or column
# default behaviour
# Defualt it is conisder index or column
# Doc string shift+tab

In [57]:
# lables,axis=0
# axis=0 index drop
# axis=1 clumn drop
df.drop('City') # City consider as index

KeyError: "['City'] not found in axis"

In [59]:
df.drop('City',axis=1)

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [ ]:
df.drop(lables,axis)
df.drop('City',axis=0) # Index drop error
df.drop('City',axis=1) # Clumn drop

df.drop(columns=['City'])
df.drop(<arguments>)
df.drop(a,b,c,d)
df.drop(2)  # 2 == column  2 == index
df.drop(2,axis=0) # label 2 it is a index
df.drop('City')  # City is a index
df.drop('City',axis=1)
#################################
df.drop(columns=['City'])
df.drop(index=[2])

In [ ]:
df.drop('City')
df.drop('City',axis=1)
df.drop(columns=['City'])
df.drop(2)
df.drop(2,axis=1)
df.drop(2,axis=0)
df.drop(index=[2])

In [65]:
df.drop('City',axis=1,inplace=True)
# inplace = False
# inplace = True overwrite the output in same df

In [67]:
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [ ]:
**Step-6: rename**

- rename the column 

- rename the index

In [69]:
d={'Names':['Ramesh','Suresh','Sathish'],
  'Age':[20,22,24],
   'City':['Hyd','Pune','Delhi']}
df=pd.DataFrame(d)
df

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Delhi

In [75]:
#df.rename(mapper)
# mapper means dictionary
c={'City':'Citi'}
df.rename(c, axis=1)  # 1 level

df.rename(columns=c)  # 2 level

     Names  Age   Citi
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Delhi

**Step-7: Save the datarame**

- .csv 

- .xlsx

- where you want to save: directory

- on what name you want save: name of the file

- on what extension you can use: .csv,.xlsx

- differnt location : "C:\Users\omkar\OneDrive\Documents\Gen_AI\df1.csv"

- "C:\Users\omkar\OneDrive\Documents\Gen_AI\df1.xlsx"

- same location: no need to provide directory: 'df1.csv'

In [79]:
df.to_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\df1.csv",index=False)
df.to_csv('df1.csv',index=False)

In [81]:
df.to_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\df2.csv")

**Step-8:How to read a Dataframe**

In [84]:
pd.read_csv(r"C:\Users\omkar\OneDrive\Documents\Gen_AI\df1.csv")
pd.read_csv('df1.csv')

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Delhi

In [ ]:
pd.read_excel(<full path>)